const industries = [
  "Finance-Publ Inv Fd-Glbl",
  "Food-Packaged",
  "Telecom-Fiber Optics",
  "Computer Sftwr-Enterprse",
  "Banks-Southeast",
  "Elec-Scientific/Msrng",
  "Finance-Investment Mgmt",
  "Leisure-Lodging",
  "Machinery-Mtl Hdlg/Autmn",
  "Containers/Packaging",
  "Transportation-Airline",
  "Retail-Department Stores",
  "Retail-Apparel/Shoes/Acc",
  "Funeral Svcs & Rel",
  "Leisure-Travel Booking",
  "Security/Sfty",
  "Comml Svcs-Staffing",
  "Oil&Gas-Transprt/Pipelne",
  "Leisure-Gaming/Equip",
  "Mining-Gold/Silver/Gems",
  "Retail/Whlsle-Automobile",
  "Bldg-Constr Prds/Misc",
  "Telecom Svcs- Foreign",
  "Diversified Operations",
  "Finance-Invest Bnk/Bkrs",
  "Retail/Whlsle-Auto Parts",
  "Oil&Gas-Royalty Trust",
  "Paper & Paper Products",
  "Computer Sftwr-Database",
  "Finance-Publ Inv Fd-Eqt",
  "Finance-Property REIT",
  "Bldg-Resident/Comml",
  "Insurance-Acc & Health",
  "Oil&Gas-Field Services",
  "Oil&Gas-Machinery/Equip",
  "Medical-Research Eqp/Svc",
  "Computer-Integrated Syst",
  "Chemicals-Plastics",
  "Leisure-Movies & Related",
  "Retail/Whlsle-Bldg Prds",
  "Telecom-Cable/Satl Eqp",
  "Food-Misc Preparation",
  "Retail-Drug Stores",
  "Food-Grain & Related",
  "Pollution Control",
  "Wholesale-Food",
  "Trucks & Parts-Hvy Duty",
  "Retail/Whlsle-Jewelry",
  "Media-Books",
  "Medical-Outpnt/Hm Care",
  "Medical-Whlsle Drg/Suppl",
  "Telecom-Consumer Prods",
  "Elec-Semicondctor Fablss",
  "Bldg-A/C & Heating Prds",
  "Medical-Supplies",
  "Energy-Coal",
  "Finance-Publ Inv Fd-Bal",
  "Medical-Biomed/Biotech",
  "Finance-Mortgage REIT",
  "Finance-Mrtg&Rel Svc",
  "Transportation-Truck",
  "Food-Confectionery",
  "Oil&Gas-Refining/Mktg",
  "Retail-Home Furnishings",
  "Comml Svcs-Leasing",
  "Insurance-Brokers",
  "Auto Manufacturers",
  "Banks-Money Center",
  "Energy-Alternative/Other",
  "Oil&Gas-U S Expl&Prod",
  "Bldg-Mobile/Mfg & Rv",
  "Food-Dairy Products",
  "Steel-Specialty Alloys",
  "Machinery-Gen Industrial",
  "Medical-Managed Care",
  "Retail-Specialty",
  "Elec-Semiconductor Mfg",
  "Medical-Diversified",
  "Computer-Tech Services",
  "Oil&Gas-Drilling",
  "Bldg-Hand Tools",
  "Computer Sftwr-Medical",
  "Apparel-Clothing Mfg",
  "Bldg-Heavy Construction",
  "Computer-Networking",
  "Computer Sftwr-Security",
  "Comml Svcs-Advertising",
  "Transportation-Rail",
  "Machinery-Farm",
  "Telecom Svcs-Integrated",
  "Utility-Water Supply",
  "Retail-Mail Order&Direct",
  "Retail-Super/Mini Mkts",
  "Medical-Ethical Drugs",
  "Aerospace/Defense",
  "Chemicals-Specialty",
  "Finance-Blank Check",
  "Oil&Gas-Cdn Expl&Prod",
  "Leisure-Products",
  "Office Supplies Mfg",
  "Computer Sftwr-Design",
  "Elec-Misc Products",
  "Finance-ETF / ETN",
  "Wholesale-Electronics",
  "Beverages-Alcoholic",
  "Telecom Svcs-Cable/Satl",
  "Hsehold-Appliances/Wares",
  "Bldg-Cement/Concrt/Ag",
  "Energy-Solar",
  "Bldg-Wood Prds",
  "Utility-Diversified",
  "Consumer Prod-Specialty",
  "Auto/Truck-Replace Parts",
  "Computer-Data Storage",
  "Retail-Major Disc Chains",
  "Soap & Clng Preparatns",
  "Chemicals-Paints",
  "Metal Prds-Distributor",
  "Cosmetics/Personal Care",
  "Machinery-Constr/Mining",
  "Transportation-Logistics",
  "Banks-Foreign",
  "Transport-Air Freight",
  "Auto/Truck-Original Eqp",
  "Telecom Svcs-Wireless",
  "Finance-Commercial Loans",
  "Internet-Network Sltns",
  "Leisure-Toys/Games/Hobby",
  "Metal Proc & Fabrication",
  "Banks-Midwest",
  "Transportation-Ship",
  "Financial Svcs-Specialty",
  "Media-Newspapers",
  "Insurance-Diversified",
  "Mining-Metal Ores",
  "Retail-Consumer Elec",
  "Elec-Semiconductor Equip",
  "Consumer Prod-Electronic",
  "Finance-CrdtCard/PmtPr",
  "Leisure-Services",
  "Retail-Discount&Variety",
  "Media-Periodicals",
  "Telecom-Infrastructure",
  "Medical-Generic Drugs",
  "Machinery-Tools & Rel",
  "Medical-Hospitals",
  "Comml Svcs-Document Mgmt",
  "Comp Sftwr-Spec Enterprs",
  "Banks-West/Southwest",
  "Utility-Gas Distribution",
  "Comml Svcs-Consulting",
  "Electronic-Parts",
  "Oil&Gas-Integrated",
  "Beverages-Non-Alcoholic",
  "Computer Sftwr-Edu/Media",
  "Banks-Northeast",
  "Tobacco",
  "Comml Svcs-Healthcare",
  "Consumer Svcs-Education",
  "Retail/Whlsle-Office Sup",
  "Banks-Super Regional",
  "Elec-Contract Mfg",
  "Retail-Leisure Products",
  "Auto/Truck-Tires & Misc",
  "Computer-Hardware/Perip",
  "Apparel-Shoes & Rel Mfg",
  "Electrical-Power/Equipmt",
  "Insurance-Life",
  "Media-Diversified",
  "Insurance-Prop/Cas/Titl",
  "Chemicals-Basic",
  "Steel-Producers",
  "Finance-Savings & Loan",
  "Oil&Gas-Intl Expl&Prod",
  "Real Estate Dvlpmt/Ops",
  "Retail-Internet",
  "Finance-Publ Inv Fd-Bond",
  "Transportation-Equip Mfg",
  "Utility-Electric Power",
  "Hsehold/Office Furniture",
  "Computer Sftwr-Gaming",
  "Internet-Content",
  "Computer Sftwr-Desktop",
  "Medical-Services",
  "Bldg-Maintenance & Svc",
  "Comml Svcs-Market Rsrch",
  "Comml Svcs-Outsourcing",
  "Computer Sftwr-Financial",
  "Medical-Products",
  "Agricultural Operations",
  "Food-Meat Products",
  "Finance-Consumer Loans",
  "Media-Radio/Tv",
  "Medical-Long-term Care",
  "Retail-Restaurants",
  "Chemicals-Agricultural",
  "Medical-Systems/Equip",
];

export default industries;
